"""
Autonomous Heartbeat Engine — JARVIS's always-on background awareness.

Like Iron Man's JARVIS, this module keeps JARVIS alive between prompts.
It continuously monitors system state, detects context changes, and
generates proactive alerts when critical events occur.

The heartbeat runs as an async background daemon inside the JARVIS server
process, publishing events to an internal event bus that the Web HUD,
voice engine, and agent loop can consume.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import platform
import subprocess
import threading
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import StrEnum
from pathlib import Path
from typing import Any, Callable

from jarvis.paths import get_data_dir

log = logging.getLogger(__name__)

# ── Configuration ────────────────────────────────────────────────────────────

HEARTBEAT_INTERVAL_SYSTEM = int(os.environ.get("JARVIS_HEARTBEAT_SYSTEM_INTERVAL", "30"))
HEARTBEAT_INTERVAL_CONTEXT = int(os.environ.get("JARVIS_HEARTBEAT_CONTEXT_INTERVAL", "60"))
HEARTBEAT_INTERVAL_CALENDAR = int(os.environ.get("JARVIS_HEARTBEAT_CALENDAR_INTERVAL", "300"))

BATTERY_CRITICAL_THRESHOLD = 10
BATTERY_LOW_THRESHOLD = 20
DISK_LOW_THRESHOLD_GB = 5
RAM_HIGH_THRESHOLD_PERCENT = 90
CPU_SUSTAINED_THRESHOLD_PERCENT = 85
CPU_SUSTAINED_DURATION_SECONDS = 120
IDLE_AWAY_THRESHOLD_MINUTES = 5


# ── Event Types ──────────────────────────────────────────────────────────────

class HeartbeatEventType(StrEnum):
    SYSTEM_TELEMETRY = "system_telemetry"
    BATTERY_CRITICAL = "battery_critical"
    BATTERY_LOW = "battery_low"
    DISK_LOW = "disk_low"
    RAM_HIGH = "ram_high"
    CPU_SUSTAINED_HIGH = "cpu_sustained_high"
    THERMAL_THROTTLE = "thermal_throttle"
    USER_ARRIVED = "user_arrived"
    USER_DEPARTED = "user_departed"
    CONTEXT_CHANGE = "context_change"
    MEETING_UPCOMING = "meeting_upcoming"
    MORNING_DETECTED = "morning_detected"
    BREAK_SUGGESTED = "break_suggested"
    SESSION_MILESTONE = "session_milestone"


class AlertUrgency(StrEnum):
    CRITICAL = "critical"      # Immediate voice/notification (score > 7)
    IMPORTANT = "important"    # Queue for next interaction (score 4-7)
    INFO = "info"              # Silent log for digest (score < 4)


@dataclass
class HeartbeatEvent:
    """An event generated by the heartbeat engine."""
    event_type: HeartbeatEventType
    urgency: AlertUrgency
    title: str
    message: str
    data: dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    handled: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


# ── System Monitor ───────────────────────────────────────────────────────────

class SystemMonitor:
    """Monitors CPU, RAM, disk, battery, and thermal state."""

    def __init__(self) -> None:
        self._cpu_high_since: float | None = None
        self._last_battery_alert: float = 0
        self._battery_alert_cooldown = 300  # 5 min between repeated alerts

    def poll(self) -> dict[str, Any]:
        """Gather current system telemetry."""
        telemetry: dict[str, Any] = {
            "timestamp": datetime.now().isoformat(),
            "platform": platform.system(),
            "arch": platform.machine(),
        }

        # CPU
        try:
            load = os.getloadavg()
            cpu_count = os.cpu_count() or 1
            telemetry["cpu_load_1m"] = round(load[0], 2)
            telemetry["cpu_load_5m"] = round(load[1], 2)
            telemetry["cpu_percent_approx"] = round((load[0] / cpu_count) * 100, 1)
            telemetry["cpu_count"] = cpu_count
        except (OSError, AttributeError):
            telemetry["cpu_percent_approx"] = 0

        # Memory via vm_stat (macOS) or /proc/meminfo (Linux)
        telemetry.update(self._get_memory())

        # Disk
        try:
            stat = os.statvfs("/")
            free_gb = (stat.f_bavail * stat.f_frsize) / (1024 ** 3)
            total_gb = (stat.f_blocks * stat.f_frsize) / (1024 ** 3)
            telemetry["disk_free_gb"] = round(free_gb, 1)
            telemetry["disk_total_gb"] = round(total_gb, 1)
            telemetry["disk_used_percent"] = round((1 - free_gb / total_gb) * 100, 1)
        except (OSError, ZeroDivisionError):
            pass

        # Battery (macOS)
        telemetry.update(self._get_battery())

        # Thermal
        telemetry.update(self._get_thermal())

        return telemetry

    def check_alerts(self, telemetry: dict) -> list[HeartbeatEvent]:
        """Generate alerts from telemetry data."""
        alerts: list[HeartbeatEvent] = []
        now = time.monotonic()

        # Battery alerts
        battery_pct = telemetry.get("battery_percent")
        if battery_pct is not None and not telemetry.get("battery_charging", False):
            if battery_pct <= BATTERY_CRITICAL_THRESHOLD and (now - self._last_battery_alert) > self._battery_alert_cooldown:
                alerts.append(HeartbeatEvent(
                    event_type=HeartbeatEventType.BATTERY_CRITICAL,
                    urgency=AlertUrgency.CRITICAL,
                    title="Battery Critical",
                    message=f"Sir, battery is at {battery_pct}%. I'd strongly recommend connecting to power immediately.",
                    data={"battery_percent": battery_pct},
                ))
                self._last_battery_alert = now
            elif battery_pct <= BATTERY_LOW_THRESHOLD and (now - self._last_battery_alert) > self._battery_alert_cooldown:
                alerts.append(HeartbeatEvent(
                    event_type=HeartbeatEventType.BATTERY_LOW,
                    urgency=AlertUrgency.IMPORTANT,
                    title="Battery Low",
                    message=f"Battery at {battery_pct}%, sir. You may want to plug in soon.",
                    data={"battery_percent": battery_pct},
                ))
                self._last_battery_alert = now

        # Disk space
        disk_free = telemetry.get("disk_free_gb")
        if disk_free is not None and disk_free < DISK_LOW_THRESHOLD_GB:
            alerts.append(HeartbeatEvent(
                event_type=HeartbeatEventType.DISK_LOW,
                urgency=AlertUrgency.IMPORTANT,
                title="Disk Space Low",
                message=f"Only {disk_free:.1f} GB remaining on disk, sir. Consider freeing up space.",
                data={"disk_free_gb": disk_free},
            ))

        # Sustained high CPU
        cpu_pct = telemetry.get("cpu_percent_approx", 0)
        if cpu_pct > CPU_SUSTAINED_THRESHOLD_PERCENT:
            if self._cpu_high_since is None:
                self._cpu_high_since = now
            elif (now - self._cpu_high_since) > CPU_SUSTAINED_DURATION_SECONDS:
                alerts.append(HeartbeatEvent(
                    event_type=HeartbeatEventType.CPU_SUSTAINED_HIGH,
                    urgency=AlertUrgency.IMPORTANT,
                    title="Sustained High CPU",
                    message=f"CPU has been above {CPU_SUSTAINED_THRESHOLD_PERCENT}% for over {CPU_SUSTAINED_DURATION_SECONDS}s, sir. Something may be amiss.",
                    data={"cpu_percent": cpu_pct, "duration_seconds": now - self._cpu_high_since},
                ))
                self._cpu_high_since = now  # Reset to avoid spam
        else:
            self._cpu_high_since = None

        # Thermal
        if telemetry.get("thermal_throttled"):
            alerts.append(HeartbeatEvent(
                event_type=HeartbeatEventType.THERMAL_THROTTLE,
                urgency=AlertUrgency.IMPORTANT,
                title="Thermal Throttling",
                message="The system appears to be thermally throttled, sir. Performance may be degraded.",
                data={"thermal_state": telemetry.get("thermal_state", "unknown")},
            ))

        return alerts

    @staticmethod
    def _get_memory() -> dict[str, Any]:
        """Get memory info."""
        result: dict[str, Any] = {}
        try:
            # macOS: use sysctl for total, vm_stat for usage
            if platform.system() == "Darwin":
                total_out = subprocess.run(
                    ["sysctl", "-n", "hw.memsize"],
                    capture_output=True, text=True, timeout=5
                )
                if total_out.returncode == 0:
                    total_bytes = int(total_out.stdout.strip())
                    result["ram_total_gb"] = round(total_bytes / (1024 ** 3), 1)

                vm_out = subprocess.run(
                    ["vm_stat"],
                    capture_output=True, text=True, timeout=5
                )
                if vm_out.returncode == 0:
                    lines = vm_out.stdout.strip().split("\n")
                    page_size = 16384  # Default Apple Silicon
                    stats: dict[str, int] = {}
                    for line in lines[1:]:
                        parts = line.split(":")
                        if len(parts) == 2:
                            key = parts[0].strip().lower().replace(" ", "_")
                            val = parts[1].strip().rstrip(".")
                            try:
                                stats[key] = int(val)
                            except ValueError:
                                pass
                    free_pages = stats.get("pages_free", 0) + stats.get("pages_speculative", 0)
                    inactive_pages = stats.get("pages_inactive", 0)
                    free_gb = (free_pages + inactive_pages) * page_size / (1024 ** 3)
                    if "ram_total_gb" in result:
                        used_gb = result["ram_total_gb"] - free_gb
                        result["ram_used_gb"] = round(max(0, used_gb), 1)
                        result["ram_used_percent"] = round(max(0, (used_gb / result["ram_total_gb"]) * 100), 1)
            else:
                # Linux fallback
                with open("/proc/meminfo") as f:
                    meminfo = {}
                    for line in f:
                        parts = line.split(":")
                        if len(parts) == 2:
                            meminfo[parts[0].strip()] = int(parts[1].strip().split()[0])
                    total_kb = meminfo.get("MemTotal", 0)
                    available_kb = meminfo.get("MemAvailable", total_kb)
                    result["ram_total_gb"] = round(total_kb / (1024 ** 2), 1)
                    result["ram_used_gb"] = round((total_kb - available_kb) / (1024 ** 2), 1)
                    result["ram_used_percent"] = round(((total_kb - available_kb) / total_kb) * 100, 1) if total_kb else 0
        except Exception:
            log.debug("Failed to get memory info", exc_info=True)
        return result

    @staticmethod
    def _get_battery() -> dict[str, Any]:
        """Get battery info on macOS."""
        result: dict[str, Any] = {}
        if platform.system() != "Darwin":
            return result
        try:
            out = subprocess.run(
                ["pmset", "-g", "batt"],
                capture_output=True, text=True, timeout=5
            )
            if out.returncode == 0:
                text = out.stdout
                import re
                pct_match = re.search(r"(\d+)%", text)
                if pct_match:
                    result["battery_percent"] = int(pct_match.group(1))
                result["battery_charging"] = "charging" in text.lower() or "ac power" in text.lower()
                time_match = re.search(r"(\d+:\d+)\s+remaining", text)
                if time_match:
                    result["battery_time_remaining"] = time_match.group(1)
        except Exception:
            log.debug("Failed to get battery info", exc_info=True)
        return result

    @staticmethod
    def _get_thermal() -> dict[str, Any]:
        """Detect thermal throttling on macOS."""
        result: dict[str, Any] = {"thermal_throttled": False}
        if platform.system() != "Darwin":
            return result
        try:
            out = subprocess.run(
                ["pmset", "-g", "therm"],
                capture_output=True, text=True, timeout=5
            )
            if out.returncode == 0:
                text = out.stdout.lower()
                if "cpu_speed_limit" in text:
                    import re
                    limit_match = re.search(r"cpu_speed_limit\s*=\s*(\d+)", text)
                    if limit_match:
                        limit = int(limit_match.group(1))
                        result["thermal_cpu_limit"] = limit
                        result["thermal_throttled"] = limit < 100
                        result["thermal_state"] = "throttled" if limit < 100 else "normal"
        except Exception:
            log.debug("Failed to get thermal info", exc_info=True)
        return result


# ── Calendar Scanner ─────────────────────────────────────────────────────────

class CalendarScanner:
    """Scans macOS Calendar for upcoming events."""

    def __init__(self) -> None:
        self._notified_events: set[str] = set()

    def get_upcoming_events(self, within_minutes: int = 15) -> list[dict[str, str]]:
        """Get calendar events happening within N minutes."""
        if platform.system() != "Darwin":
            return []
        try:
            script = f'''
            tell application "Calendar"
                set now to current date
                set later to now + ({within_minutes} * 60)
                set upcoming to {{}}
                repeat with cal in calendars
                    set evts to (every event of cal whose start date >= now and start date <= later)
                    repeat with evt in evts
                        set end of upcoming to (summary of evt) & "|" & ((start date of evt) as text)
                    end repeat
                end repeat
                return upcoming
            end tell
            '''
            out = subprocess.run(
                ["osascript", "-e", script],
                capture_output=True, text=True, timeout=10
            )
            if out.returncode == 0 and out.stdout.strip():
                events = []
                for item in out.stdout.strip().split(", "):
                    parts = item.split("|", 1)
                    if len(parts) == 2:
                        events.append({"summary": parts[0].strip(), "start": parts[1].strip()})
                return events
        except Exception:
            log.debug("Failed to scan calendar", exc_info=True)
        return []

    def check_alerts(self) -> list[HeartbeatEvent]:
        """Check for upcoming meeting alerts."""
        events = self.get_upcoming_events(within_minutes=15)
        alerts = []
        for evt in events:
            event_key = f"{evt['summary']}_{evt['start']}"
            if event_key not in self._notified_events:
                self._notified_events.add(event_key)
                alerts.append(HeartbeatEvent(
                    event_type=HeartbeatEventType.MEETING_UPCOMING,
                    urgency=AlertUrgency.IMPORTANT,
                    title="Meeting Soon",
                    message=f"Sir, you have \"{evt['summary']}\" coming up at {evt['start']}.",
                    data=evt,
                ))
        # Prune old notifications (keep last 50)
        if len(self._notified_events) > 50:
            self._notified_events = set(list(self._notified_events)[-25:])
        return alerts


# ── Event Bus ────────────────────────────────────────────────────────────────

class HeartbeatEventBus:
    """Thread-safe event bus for heartbeat events with subscriber support."""

    def __init__(self, max_events: int = 200) -> None:
        self._events: list[HeartbeatEvent] = []
        self._subscribers: list[Callable[[HeartbeatEvent], None]] = []
        self._lock = threading.Lock()
        self._max_events = max_events

    def publish(self, event: HeartbeatEvent) -> None:
        """Publish an event to all subscribers."""
        with self._lock:
            self._events.append(event)
            if len(self._events) > self._max_events:
                self._events = self._events[-self._max_events:]
        for subscriber in self._subscribers:
            try:
                subscriber(event)
            except Exception:
                log.debug("Subscriber error", exc_info=True)

    def subscribe(self, callback: Callable[[HeartbeatEvent], None]) -> None:
        """Register a callback for new events."""
        self._subscribers.append(callback)

    def get_pending(self, urgency: AlertUrgency | None = None, mark_handled: bool = True) -> list[HeartbeatEvent]:
        """Get unhandled events, optionally filtered by urgency."""
        with self._lock:
            pending = [
                e for e in self._events
                if not e.handled and (urgency is None or e.urgency == urgency)
            ]
            if mark_handled:
                for e in pending:
                    e.handled = True
            return pending

    def get_recent(self, count: int = 20) -> list[HeartbeatEvent]:
        """Get the most recent events."""
        with self._lock:
            return list(self._events[-count:])

    def get_digest(self) -> list[HeartbeatEvent]:
        """Get all INFO-level unhandled events for a daily digest."""
        return self.get_pending(urgency=AlertUrgency.INFO, mark_handled=True)


# ── Heartbeat Engine ─────────────────────────────────────────────────────────

class HeartbeatEngine:
    """The autonomous heartbeat that keeps JARVIS alive between prompts.

    Runs as a background thread, continuously monitoring system state,
    detecting context changes, and publishing events to the bus.

    Usage:
        engine = get_heartbeat()
        engine.start()
        # ... later ...
        alerts = engine.event_bus.get_pending(urgency=AlertUrgency.CRITICAL)
    """

    def __init__(self) -> None:
        self.system_monitor = SystemMonitor()
        self.calendar_scanner = CalendarScanner()
        self.event_bus = HeartbeatEventBus()

        self._running = False
        self._thread: threading.Thread | None = None
        self._lock = threading.Lock()

        # State tracking
        self._last_telemetry: dict[str, Any] = {}
        self._morning_briefing_delivered_today: str = ""
        self._user_was_away = False
        self._state_file = get_data_dir() / "heartbeat_state.json"

        self._load_state()

    def start(self) -> None:
        """Start the heartbeat background thread."""
        with self._lock:
            if self._running:
                return
            self._running = True
            self._thread = threading.Thread(
                target=self._run_loop,
                name="jarvis-heartbeat",
                daemon=True,
            )
            self._thread.start()
            log.info("Heartbeat engine started")

    def stop(self) -> None:
        """Stop the heartbeat engine."""
        with self._lock:
            self._running = False
            self._save_state()
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=5)
        log.info("Heartbeat engine stopped")

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def last_telemetry(self) -> dict[str, Any]:
        return dict(self._last_telemetry)

    def get_status(self) -> dict[str, Any]:
        """Get heartbeat engine status for the HUD."""
        return {
            "running": self._running,
            "last_telemetry": self._last_telemetry,
            "pending_critical": len(self.event_bus.get_pending(AlertUrgency.CRITICAL, mark_handled=False)),
            "pending_important": len(self.event_bus.get_pending(AlertUrgency.IMPORTANT, mark_handled=False)),
            "morning_briefing_delivered": self._morning_briefing_delivered_today == datetime.now().strftime("%Y-%m-%d"),
        }

    def inject_proactive_context(self) -> str | None:
        """Called before each agent turn to inject any pending proactive alerts.

        Returns a system prompt section with alerts, or None if nothing pending.
        """
        critical = self.event_bus.get_pending(AlertUrgency.CRITICAL)
        important = self.event_bus.get_pending(AlertUrgency.IMPORTANT)

        if not critical and not important:
            return None

        parts = ["[PROACTIVE ALERTS — Address these naturally in your response]"]
        for evt in critical:
            parts.append(f"  🚨 CRITICAL: {evt.message}")
        for evt in important:
            parts.append(f"  ⚠️ IMPORTANT: {evt.message}")
        return "\n".join(parts)

    def should_deliver_morning_briefing(self) -> bool:
        """Check if morning briefing should be delivered on next interaction."""
        today = datetime.now().strftime("%Y-%m-%d")
        hour = datetime.now().hour
        return (
            self._morning_briefing_delivered_today != today
            and 5 <= hour < 12
        )

    def mark_morning_briefing_delivered(self) -> None:
        """Mark that the morning briefing has been delivered today."""
        self._morning_briefing_delivered_today = datetime.now().strftime("%Y-%m-%d")
        self._save_state()

    # ── Internal Loop ────────────────────────────────────────────────────────

    def _run_loop(self) -> None:
        """Main heartbeat loop running in background thread."""
        system_counter = 0
        calendar_counter = 0

        while self._running:
            try:
                # System telemetry (every HEARTBEAT_INTERVAL_SYSTEM seconds)
                if system_counter % HEARTBEAT_INTERVAL_SYSTEM == 0:
                    telemetry = self.system_monitor.poll()
                    self._last_telemetry = telemetry

                    # Check for system alerts
                    alerts = self.system_monitor.check_alerts(telemetry)
                    for alert in alerts:
                        self.event_bus.publish(alert)

                    # Detect user arrival/departure via idle detection
                    self._check_user_presence()

                    # Check for morning
                    if self.should_deliver_morning_briefing():
                        self.event_bus.publish(HeartbeatEvent(
                            event_type=HeartbeatEventType.MORNING_DETECTED,
                            urgency=AlertUrgency.INFO,
                            title="Morning Detected",
                            message="New day detected. Morning briefing ready.",
                        ))

                # Calendar scan (every HEARTBEAT_INTERVAL_CALENDAR seconds)
                if calendar_counter % HEARTBEAT_INTERVAL_CALENDAR == 0:
                    cal_alerts = self.calendar_scanner.check_alerts()
                    for alert in cal_alerts:
                        self.event_bus.publish(alert)

                system_counter += 1
                calendar_counter += 1
                time.sleep(1)  # Base tick: 1 second

            except Exception:
                log.debug("Heartbeat tick error", exc_info=True)
                time.sleep(5)

    def _check_user_presence(self) -> None:
        """Detect user arrival/departure transitions."""
        try:
            if platform.system() != "Darwin":
                return
            out = subprocess.run(
                ["ioreg", "-c", "IOHIDSystem"],
                capture_output=True, text=True, timeout=5
            )
            if out.returncode != 0:
                return
            import re
            match = re.search(r"HIDIdleTime\"\s*=\s*(\d+)", out.stdout)
            if not match:
                return
            idle_ns = int(match.group(1))
            idle_seconds = idle_ns / 1_000_000_000
            is_away = idle_seconds > (IDLE_AWAY_THRESHOLD_MINUTES * 60)

            if self._user_was_away and not is_away:
                # User just returned
                self.event_bus.publish(HeartbeatEvent(
                    event_type=HeartbeatEventType.USER_ARRIVED,
                    urgency=AlertUrgency.INFO,
                    title="User Returned",
                    message="Welcome back, sir.",
                    data={"idle_seconds": idle_seconds},
                ))
            elif not self._user_was_away and is_away:
                # User just left
                self.event_bus.publish(HeartbeatEvent(
                    event_type=HeartbeatEventType.USER_DEPARTED,
                    urgency=AlertUrgency.INFO,
                    title="User Away",
                    message="User appears to have stepped away.",
                    data={"idle_seconds": idle_seconds},
                ))

            self._user_was_away = is_away
        except Exception:
            log.debug("User presence check failed", exc_info=True)

    def _load_state(self) -> None:
        """Load persisted heartbeat state."""
        try:
            if self._state_file.exists():
                data = json.loads(self._state_file.read_text(encoding="utf-8"))
                self._morning_briefing_delivered_today = data.get("morning_briefing_delivered_today", "")
        except Exception:
            log.debug("Failed to load heartbeat state", exc_info=True)

    def _save_state(self) -> None:
        """Persist heartbeat state."""
        try:
            self._state_file.parent.mkdir(parents=True, exist_ok=True)
            self._state_file.write_text(
                json.dumps({
                    "morning_briefing_delivered_today": self._morning_briefing_delivered_today,
                    "last_save": datetime.now().isoformat(),
                }),
                encoding="utf-8",
            )
        except Exception:
            log.debug("Failed to save heartbeat state", exc_info=True)


# ── Tool Definitions ─────────────────────────────────────────────────────────

HEARTBEAT_TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "get_heartbeat_status",
            "description": "Get JARVIS heartbeat engine status including system telemetry, pending alerts, and uptime.",
            "parameters": {"type": "object", "properties": {}},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_pending_alerts",
            "description": "Get any pending proactive alerts from JARVIS's background monitoring (battery, disk, CPU, meetings).",
            "parameters": {"type": "object", "properties": {}},
        },
    },
]


def tool_get_heartbeat_status() -> str:
    """Execute get_heartbeat_status tool."""
    hb = get_heartbeat()
    return json.dumps(hb.get_status(), indent=2)


def tool_get_pending_alerts() -> str:
    """Execute get_pending_alerts tool."""
    hb = get_heartbeat()
    critical = hb.event_bus.get_pending(AlertUrgency.CRITICAL, mark_handled=False)
    important = hb.event_bus.get_pending(AlertUrgency.IMPORTANT, mark_handled=False)
    alerts = [e.to_dict() for e in (critical + important)]
    return json.dumps(alerts, indent=2)


HEARTBEAT_DISPATCH = {
    "get_heartbeat_status": tool_get_heartbeat_status,
    "get_pending_alerts": tool_get_pending_alerts,
}


# ── Singleton ────────────────────────────────────────────────────────────────

_heartbeat_instance: HeartbeatEngine | None = None
_heartbeat_lock = threading.Lock()


def get_heartbeat() -> HeartbeatEngine:
    """Get the global heartbeat engine singleton."""
    global _heartbeat_instance
    with _heartbeat_lock:
        if _heartbeat_instance is None:
            _heartbeat_instance = HeartbeatEngine()
        return _heartbeat_instance


__all__ = [
    "HeartbeatEngine",
    "HeartbeatEvent",
    "HeartbeatEventType",
    "HeartbeatEventBus",
    "AlertUrgency",
    "SystemMonitor",
    "CalendarScanner",
    "HEARTBEAT_TOOL_DEFINITIONS",
    "HEARTBEAT_DISPATCH",
    "get_heartbeat",
]
