"""
Document Tools — PPT, PDF, and Markdown document generation.
Gives Jarvis the ability to create presentations and documents.
"""

import re
from pathlib import Path
from datetime import datetime


# ── Tool Definitions ─────────────────────────────────────────────────────────

DOCUMENT_TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "create_presentation",
            "description": "Create a PowerPoint (.pptx) presentation with slides. Each slide has a title and bullet points.",
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "Presentation title."},
                    "slides": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "title": {"type": "string", "description": "Slide title."},
                                "bullets": {"type": "array", "items": {"type": "string"}, "description": "Bullet points."},
                            },
                        },
                        "description": "List of slides, each with a title and bullet points.",
                    },
                    "output_path": {"type": "string", "description": "Output file path (default: ~/Desktop/)."},
                },
                "required": ["title", "slides"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "create_document",
            "description": "Create a Markdown document and save it to disk.",
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "Document title."},
                    "content": {"type": "string", "description": "Document content in Markdown format."},
                    "output_path": {"type": "string", "description": "Output file path (default: ~/Desktop/)."},
                },
                "required": ["title", "content"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "create_spreadsheet",
            "description": "Create a CSV spreadsheet from structured data.",
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "Spreadsheet title (used for filename)."},
                    "headers": {"type": "array", "items": {"type": "string"}, "description": "Column headers."},
                    "rows": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}, "description": "Data rows."},
                    "output_path": {"type": "string", "description": "Output file path (default: ~/Desktop/)."},
                },
                "required": ["title", "headers", "rows"],
            },
        },
    },
]


# ── Tool Implementations ─────────────────────────────────────────────────────

def tool_create_presentation(title: str, slides: list[dict], output_path: str = "") -> str:
    """Create a PowerPoint presentation using python-pptx."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
    except ImportError:
        return "❌ python-pptx not installed. Run: pip install python-pptx"

    if not output_path:
        safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')[:50]
        output_path = str(Path.home() / "Desktop" / f"{safe_title}.pptx")

    p = Path(output_path).expanduser().resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # ── Title Slide ──────────────────────────────────────────────────
    slide_layout = prs.slide_layouts[0]  # Title Slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = title
    if slide.placeholders[1]:
        slide.placeholders[1].text = f"Generated by J.A.R.V.I.S. • {datetime.now().strftime('%B %d, %Y')}"

    # ── Content Slides ───────────────────────────────────────────────
    for slide_data in slides:
        slide_layout = prs.slide_layouts[1]  # Title and Content
        slide = prs.slides.add_slide(slide_layout)

        # Title
        slide.shapes.title.text = slide_data.get("title", "")

        # Bullets
        bullets = slide_data.get("bullets", [])
        if bullets and len(slide.placeholders) > 1:
            tf = slide.placeholders[1].text_frame
            tf.clear()
            for i, bullet in enumerate(bullets):
                if i == 0:
                    tf.text = bullet
                else:
                    p_new = tf.add_paragraph()
                    p_new.text = bullet
                    p_new.level = 0

    prs.save(str(p))
    num_slides = len(slides) + 1  # +1 for title slide
    return f"✅ Presentation created: {p}\n   {num_slides} slides, titled \"{title}\""


def tool_create_document(title: str, content: str, output_path: str = "") -> str:
    """Create a markdown document."""
    if not output_path:
        safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')[:50]
        output_path = str(Path.home() / "Desktop" / f"{safe_title}.md")

    p = Path(output_path).expanduser().resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    doc_content = f"# {title}\n\n"
    doc_content += f"*Generated by J.A.R.V.I.S. on {datetime.now().strftime('%B %d, %Y at %H:%M')}*\n\n"
    doc_content += "---\n\n"
    doc_content += content

    with open(p, "w", encoding="utf-8") as f:
        f.write(doc_content)

    word_count = len(content.split())
    return f"✅ Document created: {p}\n   {word_count} words, titled \"{title}\""


def tool_create_spreadsheet(title: str, headers: list[str], rows: list[list], output_path: str = "") -> str:
    """Create a CSV spreadsheet."""
    import csv

    if not output_path:
        safe_title = re.sub(r'[^\w\s-]', '', title).strip().replace(' ', '_')[:50]
        output_path = str(Path.home() / "Desktop" / f"{safe_title}.csv")

    p = Path(output_path).expanduser().resolve()
    p.parent.mkdir(parents=True, exist_ok=True)

    with open(p, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(rows)

    return f"✅ Spreadsheet created: {p}\n   {len(rows)} rows × {len(headers)} columns"


# ── Dispatch ─────────────────────────────────────────────────────────────────

DOCUMENT_DISPATCH = {
    "create_presentation": lambda **kw: tool_create_presentation(
        kw.get("title", "Untitled"), kw.get("slides", []), kw.get("output_path", "")),
    "create_document": lambda **kw: tool_create_document(
        kw.get("title", "Untitled"), kw.get("content", ""), kw.get("output_path", "")),
    "create_spreadsheet": lambda **kw: tool_create_spreadsheet(
        kw.get("title", "Untitled"), kw.get("headers", []), kw.get("rows", []), kw.get("output_path", "")),
}
