"""The governed Amaura Studio v1 workforce registry."""

from __future__ import annotations

from jarvis.amaura.models import CompanyAgent, RiskLevel
from jarvis.amaura.prompts import PROMPT_VERSION, get_system_prompt

DOCTRINE = (
    "You are an Amaura Labs AI employee. JARVIS is your sole company orchestrator. "
    "Work only from a structured task packet, use only approved tools and data, stay "
    "within budget, attach verifiable evidence, never certify your own work, never "
    "invent facts, and escalate any action outside your authority."
)


def _agent(
    agent_id: str,
    name: str,
    department: str,
    objective: str,
    tools: tuple[str, ...],
    permissions: tuple[str, ...],
    data_access: tuple[str, ...],
    cost: int,
    risk: RiskLevel,
    reviewer: str | None,
    metrics: tuple[str, ...],
    prompt_profile: str | None = None,
) -> CompanyAgent:
    fallback = f"{DOCTRINE}\n\nROLE: {name}\nOBJECTIVE: {objective}"
    role_prompt = get_system_prompt(prompt_profile, fallback) if prompt_profile else fallback
    return CompanyAgent(
        agent_id=agent_id,
        name=name,
        department=department,
        objective=objective,
        tools=tools,
        permissions=permissions,
        data_access=data_access,
        cost_limit_cents=cost,
        max_risk=risk,
        reviewer_id=reviewer,
        performance_objectives=metrics,
        system_prompt=(f"{DOCTRINE}\n\nPROMPT VERSION: {PROMPT_VERSION}\n\n{role_prompt}" if prompt_profile else role_prompt),
    )


V1_AGENTS: tuple[CompanyAgent, ...] = (
    _agent(
        "jarvis",
        "JARVIS",
        "control_plane",
        "Translate founder direction into measurable programmes and govern every agent.",
        ("amaura_create_program", "amaura_company_status", "amaura_company_blueprint", "amaura_resource_inventory", "amaura_capability_health", "amaura_capability_plan", "amaura_execute_capability", "amaura_task_packet", "amaura_daily_briefing", "amaura_supervisor_status", "amaura_supervisor_tick"),
        ("plan", "delegate", "pause", "escalate", "request_approval"),
        ("company", "products", "clients", "research", "marketing", "decisions", "costs"),
        5000,
        RiskLevel.HIGH,
        "founder",
        ("programme outcome rate", "blocked-task age", "budget variance", "founder decision latency"),
        prompt_profile="jarvis",
    ),
    _agent(
        "opportunity_scout",
        "Opportunity Scout",
        "revenue",
        "Discover evidence-backed commercial opportunities from approved sources.",
        ("web_search", "web_fetch", "read_file", "amaura_execute_capability"),
        ("research", "draft"),
        ("public", "approved_lead_sources"),
        300,
        RiskLevel.LOW,
        "lead_qualification",
        ("qualified opportunities", "source coverage", "false-positive rate"),
        prompt_profile="opportunity_scout",
    ),
    _agent(
        "lead_qualification",
        "Lead Qualification Agent",
        "revenue",
        "Reject poor-fit work and rank viable leads by value, risk, and strategic relevance.",
        ("read_file", "recall_memory"),
        ("analyse", "recommend"),
        ("leads", "pricing_policy", "client_history"),
        250,
        RiskLevel.LOW,
        "jarvis",
        ("accepted-lead win rate", "bad-fit rejection rate"),
        prompt_profile="lead_qualification",
    ),
    _agent(
        "proposal",
        "Proposal Agent",
        "revenue",
        "Draft specific proposals grounded in verified requirements and approved pricing policy.",
        ("read_file", "create_document"),
        ("draft",),
        ("qualified_leads", "proposal_templates", "pricing_policy"),
        400,
        RiskLevel.MEDIUM,
        "jarvis",
        ("proposal acceptance rate", "unsupported-claim rate"),
        prompt_profile="proposal",
    ),
    _agent(
        "crm",
        "CRM Agent",
        "revenue",
        "Maintain lead state, communications, value, probability, follow-up, and next action.",
        ("read_file", "write_file", "amaura_transition_lead"),
        ("read_crm", "update_crm"),
        ("leads", "client_communications"),
        150,
        RiskLevel.LOW,
        "jarvis",
        ("record completeness", "overdue follow-ups"),
        prompt_profile="crm",
    ),
    _agent(
        "client_communication",
        "Client Communication Agent",
        "revenue",
        "Draft accurate client replies and updates without making unapproved commitments.",
        ("read_file", "create_document"),
        ("draft_external",),
        ("client_requirements", "client_communications", "project_status"),
        300,
        RiskLevel.MEDIUM,
        "jarvis",
        ("draft approval rate", "commitment violations"),
        prompt_profile="client_communication",
    ),
    _agent(
        "product_manager",
        "Product Manager",
        "product_engineering",
        "Turn validated needs into requirements, acceptance criteria, milestones, and releases.",
        ("read_file", "search_code", "get_project_structure"),
        ("plan", "define_acceptance_criteria"),
        ("products", "user_evidence", "roadmap"),
        400,
        RiskLevel.LOW,
        "technical_architect",
        ("acceptance-criteria pass rate", "scope change rate"),
        prompt_profile="product_manager",
    ),
    _agent(
        "technical_architect",
        "Technical Architect",
        "product_engineering",
        "Define secure, maintainable architecture, boundaries, data design, and rollback strategy.",
        ("read_file", "search_code", "get_project_structure", "analyze_code"),
        ("analyse_repo", "author_adr", "recommend"),
        ("repositories", "products", "security_policy"),
        500,
        RiskLevel.LOW,
        "qa",
        ("architecture defects", "decision reversals"),
        prompt_profile="technical_architect",
    ),
    _agent(
        "repository_intelligence",
        "Repository Intelligence Agent",
        "product_engineering",
        "Select only relevant repository context and maintain symbol and dependency maps.",
        ("read_file", "search_code", "find_files", "get_project_structure", "index_codebase_ast", "search_symbol"),
        ("read_repo", "index_repo"),
        ("repositories",),
        300,
        RiskLevel.LOW,
        "technical_architect",
        ("context precision", "wrong-file rate", "context token savings"),
        prompt_profile="repository_intelligence",
    ),
    _agent(
        "builder",
        "Builder Agent",
        "product_engineering",
        "Implement approved plans in isolated workspaces without self-certification.",
        ("read_file", "search_code", "write_file", "run_command", "run_tests"),
        ("read_repo", "write_branch", "run_safe_commands"),
        ("assigned_repository", "approved_plan"),
        1200,
        RiskLevel.MEDIUM,
        "qa",
        ("first-pass QA rate", "regression rate", "cost per accepted task"),
        prompt_profile="builder",
    ),
    _agent(
        "patch_engineer",
        "Patch Engineer",
        "product_engineering",
        "Apply exact, pre-approved transformations and report the expected post-edit state.",
        ("read_file", "edit_file", "diff_files"),
        ("read_repo", "write_exact_patch"),
        ("approved_plan", "target_files"),
        500,
        RiskLevel.MEDIUM,
        "qa",
        ("patch application rate", "wrong-file rate", "format compliance"),
        prompt_profile="patch_engineer",
    ),
    _agent(
        "qa",
        "QA Agent",
        "product_engineering",
        "Independently verify acceptance criteria, regressions, security, and evidence.",
        ("read_file", "search_code", "run_tests", "lint_code", "analyze_code", "git_diff"),
        ("read_repo", "run_safe_commands", "approve_or_reject"),
        ("repositories", "test_evidence", "policies"),
        700,
        RiskLevel.LOW,
        "jarvis",
        ("escaped defects", "false approvals", "verification coverage"),
        prompt_profile="qa",
    ),
    _agent(
        "content_strategy",
        "Content Strategy Agent",
        "growth_media",
        "Turn verified company events into focused content opportunities and editorial plans.",
        ("read_file", "web_search"),
        ("research", "plan", "draft"),
        ("verified_company_events", "brand_policy", "marketing_metrics"),
        300,
        RiskLevel.LOW,
        "jarvis",
        ("business-qualified content ideas", "evidence coverage"),
        prompt_profile="content_strategy",
    ),
    _agent(
        "content_production",
        "Content Production Agent",
        "growth_media",
        "Create platform-ready assets from verified master sources without inventing achievements.",
        ("read_file", "create_document", "create_presentation"),
        ("draft_public",),
        ("approved_content_brief", "verified_evidence", "brand_policy"),
        500,
        RiskLevel.MEDIUM,
        "jarvis",
        ("approval rate", "claim correction rate", "attributed outcomes"),
        prompt_profile="content_production",
    ),
    _agent(
        "research_evaluation",
        "Research and Evaluation Agent",
        "ai_research",
        "Run hypothesis-led, reproducible research and independently report regressions and costs.",
        ("web_search", "web_fetch", "read_pdf", "read_file", "run_command", "run_tests"),
        ("research", "run_sandboxed_experiment", "evaluate"),
        ("research", "datasets", "models", "experiment_registry"),
        1500,
        RiskLevel.MEDIUM,
        "qa",
        ("reproducible experiments", "regressions detected", "cost per accepted improvement"),
        prompt_profile="research_evaluation",
    ),
)


REVENUE_AGENTS: tuple[CompanyAgent, ...] = (
    _agent(
        "revenue_orchestrator",
        "Revenue Workforce Orchestrator",
        "revenue",
        "Run an ethical, measurable loop from one campaign through won-project handoff.",
        ("read_file", "web_search", "amaura_company_status", "amaura_list_tasks"),
        ("plan", "delegate", "recommend", "request_approval"),
        ("campaigns", "leads", "evidence", "messages", "pipeline_metrics", "portfolio"),
        600,
        RiskLevel.MEDIUM,
        "jarvis",
        ("qualified pipeline value", "positive reply rate", "sales-cycle length", "won revenue"),
        prompt_profile="revenue_orchestrator",
    ),
    _agent(
        "chief_revenue_officer",
        "Chief Revenue Officer",
        "revenue",
        "Create predictable, profitable project revenue without compromising Amaura's reputation.",
        ("read_file", "recall_memory", "amaura_company_status", "amaura_list_tasks"),
        ("analyse", "prioritise", "recommend_pricing", "request_approval"),
        ("campaigns", "leads", "proposals", "pricing_policy", "portfolio", "revenue_metrics"),
        700,
        RiskLevel.MEDIUM,
        "jarvis",
        ("qualified reply rate", "proposal conversion", "average project value", "recurring revenue"),
        prompt_profile="chief_revenue_officer",
    ),
    _agent(
        "campaign_manager",
        "Campaign Manager",
        "revenue",
        "Configure one bounded offer, segment, region, proof set, and daily operating envelope.",
        ("read_file", "recall_memory"),
        ("plan", "configure_campaign"),
        ("campaigns", "portfolio", "pricing_policy"),
        200,
        RiskLevel.LOW,
        "chief_revenue_officer",
        ("campaign completeness", "target precision", "limit compliance"),
        prompt_profile="campaign_manager",
    ),
    _agent(
        "lead_scout",
        "Lead Scout",
        "revenue",
        "Discover public, campaign-fit businesses without restricted scraping or guessed contact data.",
        ("web_search", "web_fetch", "read_file", "amaura_discover_lead"),
        ("research", "draft"),
        ("public", "campaigns", "lead_domains"),
        250,
        RiskLevel.LOW,
        "prospect_research",
        ("unique qualified discoveries", "duplicate rate", "source coverage"),
        prompt_profile="lead_discovery_outreach",
    ),
    _agent(
        "prospect_research",
        "Prospect Research Analyst",
        "revenue",
        "Extract source-linked business evidence from the minimum necessary public pages.",
        ("web_fetch", "read_file", "amaura_record_lead_evidence"),
        ("research", "extract"),
        ("public", "campaigns", "leads"),
        250,
        RiskLevel.LOW,
        "compliance_reviewer",
        ("evidence completeness", "claim precision", "pages per lead"),
        prompt_profile="prospect_research",
    ),
    _agent(
        "contact_resolver",
        "Contact Resolver",
        "revenue",
        "Locate verifiable public business contact routes and never infer private addresses.",
        ("web_fetch", "read_file"),
        ("research", "recommend"),
        ("public", "leads"),
        150,
        RiskLevel.LOW,
        "compliance_reviewer",
        ("verified contact rate", "guessed-address rate"),
        prompt_profile="contact_resolver",
    ),
    _agent(
        "portfolio_matcher",
        "Portfolio Matcher",
        "revenue",
        "Select at most two genuinely relevant Amaura proof assets for each prospect.",
        ("read_file", "recall_memory", "amaura_score_lead", "amaura_transition_lead"),
        ("analyse", "recommend"),
        ("leads", "portfolio", "verified_evidence"),
        100,
        RiskLevel.LOW,
        "opportunity_analyst",
        ("proof relevance", "unsupported proof rate"),
        prompt_profile="portfolio_matcher",
    ),
    _agent(
        "opportunity_analyst",
        "Opportunity Analyst",
        "revenue",
        "Turn verified evidence into one specific, non-invented commercial opportunity.",
        ("read_file", "recall_memory"),
        ("analyse", "recommend"),
        ("leads", "evidence", "portfolio"),
        180,
        RiskLevel.LOW,
        "compliance_reviewer",
        ("observation acceptance", "unsupported-claim rate"),
        prompt_profile="opportunity_analyst",
    ),
    _agent(
        "outreach_writer",
        "Outreach Writer",
        "revenue",
        "Prepare concise, personalised, proof-based outreach for human approval.",
        ("read_file", "create_document", "amaura_stage_outreach"),
        ("draft_external",),
        ("qualified_leads", "evidence", "portfolio", "brand_policy"),
        250,
        RiskLevel.MEDIUM,
        "compliance_reviewer",
        ("approval rate", "qualified reply rate", "rewrite rate"),
        prompt_profile="lead_discovery_outreach",
    ),
    _agent(
        "compliance_reviewer",
        "Revenue Compliance and Quality Reviewer",
        "revenue",
        "Reject unsupported claims, spam, irrelevant proof, opt-out violations, and duplicate contact.",
        ("read_file", "recall_memory", "amaura_transition_lead"),
        ("analyse", "approve_or_reject"),
        ("leads", "evidence", "messages", "policies"),
        180,
        RiskLevel.LOW,
        "jarvis",
        ("false approvals", "policy escape rate", "review precision"),
        prompt_profile="compliance_reviewer",
    ),
    _agent(
        "approval_coordinator",
        "Human Approval Coordinator",
        "control_plane",
        "Present complete approval cards and execute only the founder's authenticated decision.",
        ("read_file",),
        ("request_approval", "create_draft_after_approval"),
        ("qualified_leads", "evidence", "messages", "approvals"),
        100,
        RiskLevel.HIGH,
        "founder",
        ("approval packet completeness", "stale approval rate", "unauthorised action rate"),
        prompt_profile="approval_coordinator",
    ),
    _agent(
        "sales_closer",
        "Senior Sales Closer",
        "revenue",
        "Convert qualified replies into profitable, bounded paid milestones and retainers.",
        ("read_file", "create_document", "recall_memory"),
        ("analyse", "draft_external", "recommend_pricing"),
        ("qualified_leads", "communications", "portfolio", "pricing_policy"),
        450,
        RiskLevel.MEDIUM,
        "jarvis",
        ("close rate", "advance-payment rate", "scope defects", "recurring revenue"),
        prompt_profile="sales_closer",
    ),
    _agent(
        "followup",
        "Follow-up Agent",
        "revenue",
        "Prepare at most two relevant follow-ups and stop immediately on rejection or opt-out.",
        ("read_file", "create_document", "amaura_register_content_asset"),
        ("draft_external",),
        ("messages", "leads", "evidence"),
        120,
        RiskLevel.MEDIUM,
        "compliance_reviewer",
        ("follow-up reply rate", "limit compliance", "opt-out compliance"),
        prompt_profile="followup",
    ),
    _agent(
        "reply_intelligence",
        "Reply Intelligence Agent",
        "revenue",
        "Classify lead replies, extract needs, and prepare grounded next actions without commitments.",
        ("read_file", "recall_memory"),
        ("analyse", "draft_external"),
        ("lead_threads", "leads", "pricing_policy"),
        180,
        RiskLevel.MEDIUM,
        "sales_closer",
        ("classification accuracy", "commitment violations", "response latency"),
        prompt_profile="reply_intelligence",
    ),
    _agent(
        "discovery",
        "Discovery and Meeting Agent",
        "revenue",
        "Prepare evidence-backed meeting briefs and turn founder notes into bounded requirements.",
        ("read_file", "create_document", "recall_memory"),
        ("analyse", "draft"),
        ("leads", "evidence", "communications", "portfolio"),
        220,
        RiskLevel.LOW,
        "sales_closer",
        ("brief completeness", "unresolved-risk capture", "next-action clarity"),
        prompt_profile="discovery",
    ),
    _agent(
        "project_handoff",
        "Won Project Handoff Agent",
        "delivery",
        "Create a complete, least-privilege delivery packet after approved commercial acceptance.",
        ("read_file", "write_file", "create_document"),
        ("draft", "create_delivery_packet"),
        ("won_leads", "approved_proposals", "client_requirements"),
        300,
        RiskLevel.MEDIUM,
        "product_manager",
        ("handoff completeness", "delivery clarification rate", "credential exposure rate"),
        prompt_profile="project_handoff",
    ),
)


CONTENT_FACTORY_AGENTS: tuple[CompanyAgent, ...] = (
    _agent(
        "marketing_head",
        "Head of Marketing and Demand Generation",
        "growth_media",
        "Turn verified Amaura work into qualified interest, authority, and commercial conversations.",
        ("read_file", "web_search", "create_document"),
        ("plan", "draft_public"),
        ("verified_company_events", "portfolio", "brand_policy", "marketing_metrics"),
        400,
        RiskLevel.MEDIUM,
        "jarvis",
        ("qualified enquiries", "portfolio clicks", "influenced revenue"),
        prompt_profile="marketing_demand_generation",
    ),
    _agent(
        "content_research",
        "Trend and Content Research Employee",
        "growth_media",
        "Find audience questions, demand, credible sources, content gaps, and Amaura's unique angle.",
        ("web_search", "web_fetch", "read_file", "amaura_register_content_asset", "amaura_execute_capability"),
        ("research", "draft"),
        ("public", "verified_company_events", "portfolio"),
        250,
        RiskLevel.LOW,
        "content_strategy",
        ("source quality", "content-gap precision", "business relevance"),
        prompt_profile="content_research",
    ),
    _agent(
        "scriptwriter",
        "Scriptwriting Employee",
        "growth_media",
        "Create factual long-form scripts, scene plans, claims, demonstrations, hooks, and metadata.",
        ("read_file", "create_document"),
        ("draft_public",),
        ("approved_content_brief", "verified_evidence", "brand_policy"),
        350,
        RiskLevel.MEDIUM,
        "media_qa",
        ("claim accuracy", "script approval rate", "repurposing yield"),
        prompt_profile="scriptwriter",
    ),
    _agent(
        "demo_operator",
        "Product Demo Employee",
        "growth_media",
        "Record reproducible product demonstrations with secrets and private data excluded.",
        ("read_file", "run_command", "amaura_register_content_asset", "amaura_execute_capability"),
        ("run_safe_commands", "record_demo"),
        ("approved_demo_plan", "assigned_product"),
        250,
        RiskLevel.MEDIUM,
        "media_qa",
        ("demo success rate", "retake rate", "secret exposure rate"),
        prompt_profile="demo_operator",
    ),
    _agent(
        "voice_production",
        "Voice Production Employee",
        "growth_media",
        "Produce consistent, licensed narration without impersonation or unauthorised voice cloning.",
        ("read_file", "run_command", "amaura_register_content_asset", "amaura_execute_capability"),
        ("run_safe_commands", "render_audio"),
        ("approved_script", "pronunciation_dictionary"),
        200,
        RiskLevel.LOW,
        "media_qa",
        ("pronunciation accuracy", "audio defects", "licence compliance"),
        prompt_profile="voice_production",
    ),
    _agent(
        "asset_curator",
        "Media Asset and Licence Employee",
        "growth_media",
        "Collect only owned or licensed visuals with source, creator, terms, and retrieval evidence.",
        ("web_search", "web_fetch", "read_file", "amaura_execute_capability"),
        ("research", "download_approved_assets"),
        ("approved_asset_sources", "brand_policy", "content_campaigns"),
        250,
        RiskLevel.LOW,
        "media_qa",
        ("licence completeness", "asset relevance", "attribution defects"),
        prompt_profile="asset_curator",
    ),
    _agent(
        "video_production",
        "Video Production Employee",
        "growth_media",
        "Assemble approved recordings, narration, assets, captions, and templates into validated renders.",
        ("read_file", "run_command", "amaura_execute_capability"),
        ("run_safe_commands", "render_media"),
        ("approved_campaign_assets", "render_templates"),
        600,
        RiskLevel.MEDIUM,
        "media_qa",
        ("render success", "technical defect rate", "production time"),
        prompt_profile="video_production",
    ),
    _agent(
        "shorts_editor",
        "Short-form Repurposing Employee",
        "growth_media",
        "Select standalone, high-value moments and create permission-safe vertical variants.",
        ("read_file", "run_command", "amaura_execute_capability"),
        ("run_safe_commands", "render_media"),
        ("owned_long_form", "transcripts", "brand_policy"),
        300,
        RiskLevel.MEDIUM,
        "media_qa",
        ("accepted clips", "context rejection rate", "short retention"),
        prompt_profile="shorts_editor",
    ),
    _agent(
        "thumbnail_metadata",
        "Thumbnail and Metadata Employee",
        "growth_media",
        "Create readable, deterministic thumbnail variants, accurate titles, chapters, and descriptions.",
        ("read_file", "create_document", "run_command", "amaura_register_content_asset", "amaura_execute_capability"),
        ("draft_public", "render_media"),
        ("approved_campaign_assets", "brand_policy", "verified_evidence"),
        220,
        RiskLevel.MEDIUM,
        "media_qa",
        ("mobile readability", "title accuracy", "click-through rate"),
        prompt_profile="thumbnail_metadata",
    ),
    _agent(
        "media_qa",
        "Media QA and Claims Employee",
        "growth_media",
        "Independently verify facts, privacy, licences, audio/video integrity, captions, and calls to action.",
        ("read_file", "run_command", "amaura_register_content_asset", "amaura_execute_capability"),
        ("run_safe_commands", "approve_or_reject"),
        ("campaign_assets", "verified_evidence", "licence_records", "policies"),
        350,
        RiskLevel.LOW,
        "jarvis",
        ("escaped claims", "privacy escapes", "technical defect escapes"),
        prompt_profile="media_qa",
    ),
    _agent(
        "publishing",
        "Publishing and Scheduling Employee",
        "growth_media",
        "Prepare private drafts and schedules; make nothing public without founder approval.",
        ("read_file",),
        ("draft_public", "schedule_after_approval"),
        ("approved_content", "platform_policy", "publication_calendar"),
        180,
        RiskLevel.HIGH,
        "founder",
        ("unauthorised publications", "metadata completeness", "schedule accuracy"),
        prompt_profile="publishing",
    ),
    _agent(
        "content_analytics",
        "Content Analytics and Learning Employee",
        "growth_media",
        "Measure business and audience outcomes at 24h, 72h, 7d, and 30d and preserve evidence-backed lessons.",
        ("read_file", "recall_memory", "amaura_record_content_metrics"),
        ("analyse", "recommend"),
        ("platform_analytics", "content_campaigns", "revenue_attribution"),
        200,
        RiskLevel.LOW,
        "marketing_head",
        ("lesson evidence quality", "qualified enquiries", "influenced revenue"),
        prompt_profile="content_analytics",
    ),
)


COMPANY_OPERATIONS_AGENTS: tuple[CompanyAgent, ...] = (
    _agent(
        "strategy_director",
        "Strategy Director",
        "strategy",
        "Convert Amaura's mission into a small portfolio of measurable priorities and stop low-evidence work.",
        ("read_file", "recall_memory", "web_search", "amaura_company_status", "amaura_list_tasks", "create_document"),
        ("plan", "analyse", "prioritise", "recommend"),
        ("company", "products", "research", "growth_metrics", "financial_summary"),
        450,
        RiskLevel.LOW,
        "jarvis",
        ("priority outcome rate", "portfolio focus", "stopped low-value work"),
        prompt_profile="strategy_director",
    ),
    _agent(
        "product_discovery",
        "Product Discovery Lead",
        "product",
        "Validate painful user problems before engineering investment and produce evidence-backed product briefs.",
        ("web_search", "web_fetch", "read_file", "recall_memory", "create_document"),
        ("research", "analyse", "draft", "recommend"),
        ("public", "user_evidence", "market_memory", "product_portfolio"),
        500,
        RiskLevel.LOW,
        "strategy_director",
        ("validated problems", "false-positive ideas rejected", "evidence-to-MVP conversion"),
        prompt_profile="product_discovery",
    ),
    _agent(
        "operations_manager",
        "Company Operations Manager",
        "operations",
        "Maintain operating cadence, task hygiene, capacity, documentation, and cross-department follow-through.",
        ("read_file", "recall_memory", "amaura_company_status", "amaura_list_tasks", "create_document"),
        ("plan", "analyse", "prioritise", "draft"),
        ("company", "programmes", "tasks", "decisions", "costs"),
        300,
        RiskLevel.LOW,
        "jarvis",
        ("blocked-task age", "weekly commitment completion", "operating review accuracy"),
        prompt_profile="operations_manager",
    ),
    _agent(
        "finance_controller",
        "Finance and Runway Controller",
        "finance",
        "Track burn, budgets, subscriptions, unit economics, and runway without moving funds.",
        ("read_file", "recall_memory", "amaura_company_status", "amaura_list_tasks", "create_document"),
        ("analyse", "prioritise", "recommend", "draft"),
        ("costs", "budgets", "revenue_metrics", "subscriptions", "product_metrics"),
        220,
        RiskLevel.LOW,
        "jarvis",
        ("budget variance", "runway forecast accuracy", "avoidable cost identified"),
        prompt_profile="finance_controller",
    ),
    _agent(
        "security_director",
        "Security Director",
        "security_legal",
        "Continuously verify that every capability obeys least privilege, containment, secret handling, and incident policy.",
        ("read_file", "search_code", "get_project_structure", "analyze_code", "run_tests", "lint_code", "git_diff"),
        ("analyse_repo", "approve_or_reject", "run_safe_commands", "recommend"),
        ("repositories", "security_policy", "audit_log", "incident_evidence"),
        650,
        RiskLevel.LOW,
        "jarvis",
        ("policy escapes", "mean time to contain", "security regression coverage"),
        prompt_profile="security_director",
    ),
    _agent(
        "legal_compliance",
        "Legal and Licence Operations Agent",
        "security_legal",
        "Review public claims, privacy, open-source licences, media rights, and contract drafts for human/legal escalation.",
        ("read_file", "recall_memory", "web_fetch", "create_document"),
        ("analyse", "approve_or_reject", "recommend", "draft"),
        ("policies", "licence_records", "public_claims", "contract_drafts"),
        300,
        RiskLevel.LOW,
        "jarvis",
        ("licence completeness", "claim corrections", "privacy issues detected"),
        prompt_profile="legal_compliance",
    ),
    _agent(
        "customer_success",
        "Customer Success Lead",
        "customer_success",
        "Onboard users, organise feedback, identify risk, and prepare accurate support responses without commitments.",
        ("read_file", "recall_memory", "create_document", "amaura_company_status"),
        ("analyse", "draft_external", "recommend"),
        ("users", "support_threads", "product_status", "knowledge_base"),
        300,
        RiskLevel.MEDIUM,
        "product_manager",
        ("activation rate", "feedback closure time", "retention risks surfaced"),
        prompt_profile="customer_success",
    ),
    _agent(
        "community_manager",
        "Developer Community Manager",
        "community",
        "Grow a useful, respectful developer and researcher community through evidence-backed education and support.",
        ("read_file", "web_search", "create_document", "amaura_register_content_asset", "amaura_record_content_metrics"),
        ("research", "draft_public", "analyse", "recommend"),
        ("community", "public", "approved_content", "community_metrics"),
        320,
        RiskLevel.MEDIUM,
        "marketing_head",
        ("active contributors", "helpful response rate", "community-to-user conversion"),
        prompt_profile="community_manager",
    ),
    _agent(
        "distribution_manager",
        "Distribution and Channel Manager",
        "growth_media",
        "Turn each approved master asset into a measured, channel-specific distribution plan and owned-audience growth loop.",
        ("read_file", "web_search", "create_document", "amaura_register_content_asset", "amaura_record_content_metrics"),
        ("plan", "research", "draft_public", "analyse", "recommend"),
        ("approved_content", "platform_policy", "channel_metrics", "brand_policy"),
        350,
        RiskLevel.MEDIUM,
        "marketing_head",
        ("qualified reach", "owned audience growth", "repurposing yield", "channel conversion"),
        prompt_profile="distribution_manager",
    ),
)


VENTURE_AGENTS: tuple[CompanyAgent, ...] = (
    _agent(
        "venture_director",
        "Amaura Ventures Director",
        "ventures",
        "Operate a disciplined startup studio that funds Amaura Labs without diluting the research mission.",
        ("web_search", "web_fetch", "read_file", "create_document", "amaura_company_status", "amaura_venture_dashboard", "amaura_cashflow_dashboard", "amaura_cashflow_tick", "amaura_venture_recommendation"),
        ("plan", "analyse", "recommend", "request_approval"),
        ("public", "venture_portfolio", "product_metrics", "company_strategy", "costs"),
        500,
        RiskLevel.MEDIUM,
        "jarvis",
        ("validated opportunities", "14-day decision rate", "capital efficiency", "founder attention used"),
        prompt_profile="venture_director",
    ),
    _agent(
        "venture_opportunity_researcher",
        "Venture Opportunity Researcher",
        "ventures",
        "Find narrow, evidenced product opportunities from public user pain, reviews, search demand and market gaps.",
        ("web_search", "web_fetch", "read_file", "create_document", "amaura_register_venture_opportunity"),
        ("research", "analyse", "draft"),
        ("public", "market_memory", "product_reviews", "search_signals"),
        420,
        RiskLevel.LOW,
        "venture_validation_analyst",
        ("evidenced opportunities", "duplicate idea rejection", "source quality"),
        prompt_profile="venture_opportunity_researcher",
    ),
    _agent(
        "venture_validation_analyst",
        "Venture Validation Analyst",
        "ventures",
        "Score opportunities deterministically and design the smallest experiment that can disprove demand within 14 days.",
        ("read_file", "web_search", "create_document", "amaura_company_status", "amaura_venture_dashboard", "amaura_cashflow_dashboard", "amaura_venture_recommendation"),
        ("analyse", "recommend", "define_acceptance_criteria", "draft"),
        ("venture_opportunities", "market_evidence", "distribution_metrics", "pricing_evidence"),
        360,
        RiskLevel.LOW,
        "venture_director",
        ("false-positive rejection", "time-to-decision", "experiment clarity"),
        prompt_profile="venture_validation_analyst",
    ),
    _agent(
        "venture_growth_operator",
        "Venture Distribution Operator",
        "ventures",
        "Prepare one-channel demand tests, launch assets and measurable acquisition loops for venture products.",
        ("web_search", "read_file", "create_document", "amaura_register_content_asset", "amaura_record_content_metrics", "amaura_record_venture_metric", "amaura_cashflow_dashboard"),
        ("plan", "draft_public", "analyse", "recommend"),
        ("venture_experiments", "approved_content", "channel_metrics", "brand_policy"),
        420,
        RiskLevel.MEDIUM,
        "media_qa",
        ("qualified demand", "channel conversion", "cost per validated signal"),
        prompt_profile="venture_growth_operator",
    ),
    _agent(
        "venture_portfolio_analyst",
        "Venture Portfolio and Monetisation Analyst",
        "ventures",
        "Measure retention, activation, revenue and cost, then recommend kill, iterate or double down without moving funds.",
        ("read_file", "recall_memory", "amaura_company_status", "create_document", "amaura_venture_dashboard", "amaura_cashflow_dashboard", "amaura_record_venture_metric", "amaura_record_cashflow_financial", "amaura_venture_recommendation"),
        ("analyse", "recommend", "draft"),
        ("venture_portfolio", "product_metrics", "costs", "revenue_metrics"),
        300,
        RiskLevel.LOW,
        "finance_controller",
        ("decision accuracy", "weak products killed", "winning products identified", "runway protected"),
        prompt_profile="venture_portfolio_analyst",
    ),
)


ALL_AGENTS: tuple[CompanyAgent, ...] = V1_AGENTS + REVENUE_AGENTS + CONTENT_FACTORY_AGENTS + COMPANY_OPERATIONS_AGENTS + VENTURE_AGENTS

AGENTS_BY_ID = {agent.agent_id: agent for agent in ALL_AGENTS}


def get_agent(agent_id: str) -> CompanyAgent:
    """Return a registered company agent or raise a clear error."""
    try:
        return AGENTS_BY_ID[agent_id]
    except KeyError as exc:
        raise KeyError(f"Unknown Amaura agent: {agent_id}") from exc
