from typing import Protocol, Any, ContextManager
from pathlib import Path

class CompanyStoreProtocol(Protocol):
    def close(self) -> None: ...
    def atomic_block(self) -> ContextManager[Any]: ...
    def integrity_check(self) -> dict[str, Any]: ...
    def backup(self, destination: str | Path) -> Path: ...

    # Agents
    def upsert_agent(self, definition: dict[str, Any]) -> None: ...
    def list_agents(self) -> list[dict[str, Any]]: ...
    def get_agent(self, agent_id: str) -> dict[str, Any]: ...
    def set_agent_enabled(self, agent_id: str, enabled: bool) -> dict[str, Any]: ...

    # Work Items
    def insert_work_item(self, item: dict[str, Any]) -> dict[str, Any]: ...
    def get_work_item(self, item_id: str) -> dict[str, Any]: ...
    def list_work_items(self, *, item_type: str | None = None, state: str | None = None, owner_id: str | None = None, parent_id: str | None = None, limit: int = 200) -> list[dict[str, Any]]: ...
    def update_work_item(self, item_id: str, **fields: Any) -> dict[str, Any]: ...

    # Approvals
    def create_approval(self, approval: dict[str, Any]) -> dict[str, Any]: ...
    def get_approval(self, approval_id: str) -> dict[str, Any]: ...
    def list_approvals(self, status: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    def expire_stale_approvals(self) -> int: ...
    def resolve_approval(self, approval_id: str, status: str, decided_by: str, reason: str) -> dict[str, Any]: ...

    # Events and Audit
    def publish_event(self, event_type: str, aggregate_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    def list_events(self, event_type: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    def audit(self, actor: str, action: str, resource_type: str, resource_id: str, outcome: str, details: dict[str, Any]) -> dict[str, Any]: ...

    # Executions
    def claim_next_task(self, worker_id: str, lease_seconds: int = 900, max_attempts: int = 3, workflow_id: str | None = None) -> dict[str, Any] | None: ...
    def heartbeat_execution(self, run_id: str, worker_id: str, lease_seconds: int = 900) -> dict[str, Any]: ...
    def finish_execution(self, run_id: str, worker_id: str, succeeded: bool, result: dict[str, Any] | None = None, error: str = "", retryable: bool = False, max_attempts: int = 3) -> dict[str, Any]: ...
    def recover_expired_executions(self, max_attempts: int = 3) -> list[dict[str, Any]]: ...
    def execution_status(self) -> dict[str, Any]: ...
    
    # Campaigns and Leads
    def create_campaign(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_campaign(self, campaign_id: str) -> dict[str, Any]: ...
    def list_campaigns(self) -> list[dict[str, Any]]: ...
    def upsert_lead(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def get_lead(self, lead_id: str) -> dict[str, Any]: ...
    def update_lead(self, lead_id: str, **fields: Any) -> dict[str, Any]: ...
    def list_leads(self, campaign_id: str, stage: str | None = None, limit: int = 200) -> list[dict[str, Any]]: ...

    # ... and so forth. This protocol sets the abstraction boundary.
